// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app;

namespace app.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20200705211227_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("app.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77b538b-9692-42fc-88c8-b999909e22f5"),
                            Name = "Stella",
                            Price = 0.0
                        },
                        new
                        {
                            Id = new Guid("84503a25-2bee-4809-822a-6bf07f494bca"),
                            Name = "Budweiser",
                            Price = 0.0
                        },
                        new
                        {
                            Id = new Guid("dfd14047-d6d2-4775-b553-7c1f056c8e9b"),
                            Name = "Becks",
                            Price = 0.0
                        });
                });

            modelBuilder.Entity("app.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("app.Order", b =>
                {
                    b.HasOne("app.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId");
                });
#pragma warning restore 612, 618
        }
    }
}
