// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app;

namespace app.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20200706004603_CreatedAt")]
    partial class CreatedAt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("app.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("286769d9-3a95-45d0-9ff9-4a293d8a94e1"),
                            Name = "Stella",
                            Price = 0.0
                        },
                        new
                        {
                            Id = new Guid("da35fc72-1a89-48bb-895d-165331c50e69"),
                            Name = "Budweiser",
                            Price = 0.0
                        },
                        new
                        {
                            Id = new Guid("10fd7e70-2e8a-40b8-90fb-bb9eaaaca955"),
                            Name = "Becks",
                            Price = 0.0
                        });
                });

            modelBuilder.Entity("app.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("app.Order", b =>
                {
                    b.HasOne("app.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId");
                });
#pragma warning restore 612, 618
        }
    }
}
