// <auto-generated />
using System;
using Beershop;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace app.Migrations
{
    [DbContext(typeof(BeershopContext))]
    partial class BeershopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Beershop.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e000a08d-d4a2-480b-82f4-d63270f48fd8"),
                            Name = "Stella",
                            Price = 0.0
                        },
                        new
                        {
                            Id = new Guid("ae190999-5ad5-4770-8a3e-6c17b59b6596"),
                            Name = "Budweiser",
                            Price = 0.0
                        },
                        new
                        {
                            Id = new Guid("dce03f29-3bf2-4e8b-b095-33a6f9ebf941"),
                            Name = "Becks",
                            Price = 0.0
                        });
                });

            modelBuilder.Entity("Beershop.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BeerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Beershop.Order", b =>
                {
                    b.HasOne("Beershop.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId");
                });
#pragma warning restore 612, 618
        }
    }
}
