# Concat this at the end of resource names
suffix: dev

# Resource Group
rg_location: eastus

# Storage Account
st_replication: "LRS"

# Postgres
psql_sku_name: GP_Gen5_2
psql_storage_mb: 5120
psql_backup_retention_days: 7
psql_geo_redundant_backup_enabled: false
psql_autogrow_enabled: false

psql_vnet_start: 10.0.0.0
psql_vnet_end: 10.0.0.255

# Service Bus
bus_sku: Basic

# App Plans
plan_tier: Standard
plan_sku: S1

# Web Apps
app_alwayson: false
app_servicebus_connection_string: primary

# Tags
tags:
  system: beershop
  envivonment: development