# Concat this at the end of resource names
suffix: dev

# Resource Group
rg_location: eastus

# Storage Account
st_replication: "LRS"

# SQL Server
sql_public_access_enabled: true
sql_sku_name: Basic
sql_zone_redudant: false

# Service Bus
bus_sku: Basic

# App Plans
plan_tier: Standard
plan_sku: S1

# Web Apps
app_alwayson: false
app_servicebus_connection_string: primary

# Tags
tags:
  system: beershop
  envivonment: development